[package]
name = "bridgingio-providers"
edition = "2021"
version = "0.1.0"
license = "MIT"

[dependencies]
bridgingio-artifacts = { path = "../bridgingio-artifacts" }
bridgingio-connectors = { path = "../bridgingio-connectors" }
bridgingio-domain = { path = "../bridgingio-domain" }
bridgingio-platform = { path = "../bridgingio-platform" }
bridgingio-policy = { path = "../bridgingio-policy" }
bridgingio-secrets = { path = "../bridgingio-secrets" }
